#!/bin/bash
# Image Mutation Tool - Simple Startup Guide

echo "=========================================="
echo "   Image Mutation Tool - Startup Guide"
echo "=========================================="
echo ""
echo "✅ All setup is complete!"
echo ""
echo "OPTION 1: Start Both Servers (Recommended for Development)"
echo "=========================================="
echo ""
echo "Terminal 1 - Start Backend:"
echo "  cd /home/vaishnavkoka/RE4BDD/imagemagickwebtool/backend"
echo "  source venv/bin/activate"
echo "  python3 app.py"
echo ""
echo "Terminal 2 - Start Frontend:"
echo "  cd /home/vaishnavkoka/RE4BDD/imagemagickwebtool/frontend"
echo "  npm start"
echo ""
echo "Then open: http://localhost:3000"
echo ""
echo ""
echo "OPTION 2: Quick Verification Commands"
echo "=========================================="
echo ""
echo "Check backend:"
echo "  cd /home/vaishnavkoka/RE4BDD/imagemagickwebtool/backend"
echo "  source venv/bin/activate"
echo "  python3 -m pytest tests/"
echo ""
echo "Check frontend:"
echo "  cd /home/vaishnavkoka/RE4BDD/imagemagickwebtool/frontend"
echo "  npm test"
echo ""
echo "Check API:"
echo "  curl http://localhost:5000/api/health"
echo ""
echo ""
echo "OPTION 3: Docker Deployment"
echo "=========================================="
echo ""
echo "  cd /home/vaishnavkoka/RE4BDD/imagemagickwebtool"
echo "  docker-compose up --build"
echo ""
echo "  Then open: http://localhost:3000"
echo ""
echo ""
echo "📚 READ THESE NEXT:"
echo "=========================================="
echo ""
echo "1. SETUP_VERIFICATION.md  - Full setup status"
echo "2. QUICK_START.md         - Detailed setup guide"
echo "3. TOOL_DESIGN_PLAN.md    - What this tool does"
echo "4. DEVELOPER_GUIDE.md     - How to add features"
echo ""
echo "=========================================="
echo ""
